# Generated by Django 4.2.11 on 2024-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_ratings"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="OrderItems", new_name="OrderItem",),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="Ghana", max_length=255),
            preserve_default=False,
        ),
    ]
