# Generated by Django 4.2.11 on 2024-03-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_rename_orderitems_orderitem_order_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="total_payment", new_name="total_amount",
        ),
    ]
