# Generated by Django 4.2.11 on 2024-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_total_payment_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
