# Generated by Django 4.2.11 on 2024-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_orderitem_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="image_url", new_name="image",
        ),
    ]
